#!/bin/bash
# Tests for boxcutter-boot-agent behavior.
# Validates config parsing, repo cloning logic, persona installation,
# and tapegun config generation.
# Run: bash boxcutter-boot-agent_test.sh

set -e
PASS=0
FAIL=0

assert_eq() {
    local desc="$1" expected="$2" actual="$3"
    if [ "$expected" = "$actual" ]; then
        echo "  PASS: $desc"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc (expected '$expected', got '$actual')"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local desc="$1" needle="$2" haystack="$3"
    if echo "$haystack" | grep -qF -- "$needle"; then
        echo "  PASS: $desc"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc (expected to contain '$needle')"
        FAIL=$((FAIL + 1))
    fi
}

assert_file_exists() {
    local desc="$1" path="$2"
    if [ -f "$path" ]; then
        echo "  PASS: $desc"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc (file not found: $path)"
        FAIL=$((FAIL + 1))
    fi
}

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

echo "=== Test 1: Parse agent-config JSON ==="

AGENT_CONFIG='{
  "repos": ["AndrewBudd/boxcutter", "AndrewBudd/other-repo"],
  "persona": {
    "role": "developer",
    "claude_md": ".claude/personas/developer.md",
    "instructions": "You are a developer. Write clean code."
  },
  "claude_flags": "--dangerously-skip-permissions --verbose",
  "claude_resume": "true",
  "working_dir": "/home/dev/project"
}'

REPOS=$(echo "$AGENT_CONFIG" | jq -r '.repos // [] | .[]')
REPO_COUNT=$(echo "$REPOS" | grep -c . || true)
PERSONA_CLAUDE_MD=$(echo "$AGENT_CONFIG" | jq -r '.persona.claude_md // empty')
PERSONA_INSTRUCTIONS=$(echo "$AGENT_CONFIG" | jq -r '.persona.instructions // empty')
PERSONA_ROLE=$(echo "$AGENT_CONFIG" | jq -r '.persona.role // empty')
CLAUDE_FLAGS=$(echo "$AGENT_CONFIG" | jq -r '.claude_flags // empty')
CLAUDE_RESUME=$(echo "$AGENT_CONFIG" | jq -r '.claude_resume // empty')
WORKING_DIR=$(echo "$AGENT_CONFIG" | jq -r '.working_dir // empty')

assert_eq "repo count" "2" "$REPO_COUNT"
assert_eq "first repo" "AndrewBudd/boxcutter" "$(echo "$REPOS" | head -1)"
assert_eq "second repo" "AndrewBudd/other-repo" "$(echo "$REPOS" | tail -1)"
assert_eq "persona role" "developer" "$PERSONA_ROLE"
assert_eq "persona claude_md path" ".claude/personas/developer.md" "$PERSONA_CLAUDE_MD"
assert_contains "persona instructions" "Write clean code" "$PERSONA_INSTRUCTIONS"
assert_eq "claude flags" "--dangerously-skip-permissions --verbose" "$CLAUDE_FLAGS"
assert_eq "claude resume" "true" "$CLAUDE_RESUME"
assert_eq "working dir" "/home/dev/project" "$WORKING_DIR"

echo ""
echo "=== Test 2: Empty/missing agent-config ==="

EMPTY_CONFIG="{}"
EMPTY_REPOS=$(echo "$EMPTY_CONFIG" | jq -r '.repos // [] | .[]')
EMPTY_COUNT=$(echo "$EMPTY_REPOS" | grep -c . || true)
assert_eq "empty config has 0 repos" "0" "$EMPTY_COUNT"

NULL_CONFIG="null"
NULL_REPOS=$(echo "$NULL_CONFIG" | jq -r '.repos // [] | .[]' 2>/dev/null || echo "")
NULL_COUNT=$(echo "$NULL_REPOS" | grep -c . || true)
assert_eq "null config has 0 repos" "0" "$NULL_COUNT"

echo ""
echo "=== Test 3: Single repo → ~/project ==="

SINGLE_CONFIG='{"repos": ["AndrewBudd/boxcutter"]}'
SINGLE_REPOS=$(echo "$SINGLE_CONFIG" | jq -r '.repos // [] | .[]')
SINGLE_COUNT=$(echo "$SINGLE_REPOS" | grep -c . || true)
assert_eq "single repo count" "1" "$SINGLE_COUNT"
# Single repo should use ~/project directly (not ~/projects/)
SINGLE_REPO=$(echo "$SINGLE_REPOS" | head -1)
assert_eq "single repo name" "AndrewBudd/boxcutter" "$SINGLE_REPO"

echo ""
echo "=== Test 4: Tapegun config generation ==="

TAPEGUN_CONFIG="${TMPDIR}/tapegun-config"
FLAGS="--dangerously-skip-permissions --verbose"
RESUME="true"
WORKDIR="/home/dev/project"

mkdir -p "$(dirname "$TAPEGUN_CONFIG")"
cat > "$TAPEGUN_CONFIG" <<EOCONFIG
# Generated by boxcutter-boot-agent (issue #94)
# Do not edit — this file is overwritten on each boot.
AUTOSTART_CLAUDE=true
CLAUDE_FLAGS="$FLAGS"
CLAUDE_RESUME=$RESUME
CLAUDE_WORKING_DIR="$WORKDIR"
EOCONFIG

assert_file_exists "tapegun config created" "$TAPEGUN_CONFIG"
assert_contains "config has flags" "$FLAGS" "$(cat "$TAPEGUN_CONFIG")"
assert_contains "config has resume" "CLAUDE_RESUME=true" "$(cat "$TAPEGUN_CONFIG")"
assert_contains "config has working dir" "$WORKDIR" "$(cat "$TAPEGUN_CONFIG")"
assert_contains "config has autostart" "AUTOSTART_CLAUDE=true" "$(cat "$TAPEGUN_CONFIG")"

# Verify tapegun can source it
AUTOSTART_CLAUDE=""
CLAUDE_FLAGS=""
CLAUDE_RESUME=""
CLAUDE_WORKING_DIR=""
source "$TAPEGUN_CONFIG"
assert_eq "sourced autostart" "true" "$AUTOSTART_CLAUDE"
assert_eq "sourced flags" "--dangerously-skip-permissions --verbose" "$CLAUDE_FLAGS"
assert_eq "sourced resume" "true" "$CLAUDE_RESUME"
assert_eq "sourced working dir" "/home/dev/project" "$CLAUDE_WORKING_DIR"

echo ""
echo "=== Test 5: Persona CLAUDE.md from inline instructions ==="

PERSONA_DIR="${TMPDIR}/project"
mkdir -p "$PERSONA_DIR"

PERSONA_INSTRUCTIONS="You are a developer. Write clean code."
{
    printf '# Agent Instructions\n\n%s\n' "$PERSONA_INSTRUCTIONS"
} > "${PERSONA_DIR}/CLAUDE.md"

assert_file_exists "CLAUDE.md created" "${PERSONA_DIR}/CLAUDE.md"
assert_contains "CLAUDE.md has instructions header" "# Agent Instructions" "$(cat "${PERSONA_DIR}/CLAUDE.md")"
assert_contains "CLAUDE.md has instructions body" "Write clean code" "$(cat "${PERSONA_DIR}/CLAUDE.md")"

echo ""
echo "=== Test 6: Persona CLAUDE.md from repo file ==="

# Simulate a persona file in the repo
mkdir -p "${PERSONA_DIR}/.claude/personas"
echo "# Developer Persona" > "${PERSONA_DIR}/.claude/personas/developer.md"
echo "Focus on writing tests." >> "${PERSONA_DIR}/.claude/personas/developer.md"

PERSONA_CLAUDE_MD=".claude/personas/developer.md"
SRC="${PERSONA_DIR}/${PERSONA_CLAUDE_MD}"

# Simulate the install_persona logic: prepend persona file before existing CLAUDE.md
EXISTING=$(cat "${PERSONA_DIR}/CLAUDE.md")
{
    cat "$SRC"
    printf '\n\n'
    echo "$EXISTING"
} > "${PERSONA_DIR}/CLAUDE.md"

assert_contains "CLAUDE.md starts with persona" "# Developer Persona" "$(head -1 "${PERSONA_DIR}/CLAUDE.md")"
assert_contains "CLAUDE.md still has instructions" "Agent Instructions" "$(cat "${PERSONA_DIR}/CLAUDE.md")"
assert_contains "CLAUDE.md has persona content" "Focus on writing tests" "$(cat "${PERSONA_DIR}/CLAUDE.md")"

echo ""
echo "=== Test 7: Default flags when not specified ==="

DEFAULT_FLAGS="${CLAUDE_FLAGS:-"--dangerously-skip-permissions"}"
CLAUDE_FLAGS=""
RESULT="${CLAUDE_FLAGS:-"--dangerously-skip-permissions"}"
assert_eq "default flags when empty" "--dangerously-skip-permissions" "$RESULT"

echo ""
echo "=== Test 8: Settings.json pre-trust ==="

SETTINGS_DIR="${TMPDIR}/.claude"
mkdir -p "$SETTINGS_DIR"
SETTINGS_FILE="${SETTINGS_DIR}/settings.json"
WORKDIR="/home/dev/project"

cat > "$SETTINGS_FILE" <<EOSETTINGS
{
  "permissions": {
    "allow": [],
    "deny": []
  },
  "trustedDirectories": [
    "$WORKDIR"
  ]
}
EOSETTINGS

assert_file_exists "settings.json created" "$SETTINGS_FILE"
TRUSTED=$(cat "$SETTINGS_FILE" | grep -o '/home/dev/project' | head -1)
assert_eq "settings.json has trusted dir" "/home/dev/project" "$TRUSTED"

echo ""
echo "=== Results ==="
echo "Passed: $PASS"
echo "Failed: $FAIL"
[ $FAIL -eq 0 ] && echo "All tests passed!" || exit 1
