#!/bin/bash
# Install and configure vmid on the Node VM.
# Run as root. Expects Go to be installed.
set -euo pipefail

BOXCUTTER_HOME="/var/lib/boxcutter"
VMID_SRC="${BOXCUTTER_HOME}/vmid"

# Check for 9p mount fallback
if [ ! -d "$VMID_SRC" ] && [ -d /mnt/boxcutter/vmid ]; then
  VMID_SRC="/mnt/boxcutter/vmid"
fi

echo "=== Building vmid ==="
cd "$VMID_SRC"
go build -o /usr/local/bin/vmid ./cmd/vmid/

echo "=== Configuring vmid ==="
mkdir -p /etc/vmid /run/vmid

# Config is generated by boxcutter-setup from boxcutter.yaml.
# Create a default config only if boxcutter-setup hasn't run yet.
if [ ! -f /etc/vmid/config.yaml ]; then
  cat > /etc/vmid/config.yaml <<'EOF'
listen:
  vm_port: 80
  admin_socket: /run/vmid/admin.sock

jwt:
  ttl: "10m"

log:
  level: info
  format: json
EOF
  echo "  Created default /etc/vmid/config.yaml (run boxcutter-setup to add GitHub App config)"
fi

echo "=== Installing systemd service ==="
cp "${BOXCUTTER_HOME}/systemd/vmid.service" /etc/systemd/system/ 2>/dev/null || \
  cp /mnt/boxcutter/systemd/vmid.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable vmid

echo "=== Starting vmid ==="
systemctl start vmid

echo ""
echo "vmid installed and running."
echo "  Config: /etc/vmid/config.yaml"
echo "  Socket: /run/vmid/admin.sock"
echo "  Health: curl --unix-socket /run/vmid/admin.sock http://localhost/healthz"
echo "  VMs reach vmid at http://10.0.0.1:80 via their TAP link"
